In [1]:
import numpy as np
list=[2,3,5,9,6]
np.array(list)

array([2, 3, 5, 9, 6])

In [2]:
import numpy as np
list2=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
np.array(list2)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [9]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(6,12)

array([ 6,  7,  8,  9, 10, 11])

In [15]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.random.rand(2)

array([0.51078458, 0.28440748])

In [17]:
np.random.randn(45)

array([ 0.82239371,  1.04466709,  1.36005165,  0.8224597 ,  0.4080648 ,
       -2.29279502,  1.02316203,  0.65868113,  1.25492879,  0.92386488,
        0.99950014, -0.23843166,  0.16128972,  1.05642021,  1.01984013,
        0.99403576, -1.31475408,  0.95385982,  0.53735039,  0.56832825,
        0.70573338, -0.68215684,  1.10717637,  0.36814228, -0.65567848,
        1.48931037, -1.0372132 ,  0.71693177, -0.29681817, -0.23910145,
        0.23397133, -0.97010785, -1.2339005 , -0.78417703,  0.78140567,
        0.32852397, -0.66966972, -0.30843851, -1.17322753, -0.35181313,
        1.07153762,  0.12605377,  0.17107401,  1.04858145, -1.41115174])

In [18]:
np.random.randn(9,9)

array([[-2.26486343,  0.99308188, -1.3927123 ,  1.01613984,  0.12879595,
         0.79567529,  1.59936161,  0.31675671, -0.08197556],
       [-0.66829167,  1.51770423, -0.05269163,  0.06507379,  0.5554785 ,
         0.87354906, -0.41603436, -0.01793887,  0.90988236],
       [-0.4108601 , -0.45953722,  0.67953338, -0.22240106, -0.88640274,
        -0.78424375,  1.1202587 ,  2.2347942 , -1.35013584],
       [-0.86537257, -1.37771324,  0.5010439 ,  0.28759958, -1.37777162,
         0.0371127 , -0.62366022, -0.13867877,  1.24566433],
       [-0.83502128, -0.44020246,  1.32458104,  0.74780158,  0.13203966,
         0.27756335, -1.93817379,  0.84279909,  0.04918016],
       [ 0.15745111,  1.22547178, -0.34040237, -0.91567674, -0.55100125,
        -0.6595656 , -1.76753963,  0.34905759,  1.29398131],
       [-0.50587298, -0.48499395,  0.28506166, -1.83285543,  0.51193838,
        -0.63026591,  1.45237648, -0.35419819, -1.57950606],
       [-0.37615814,  0.24818893,  0.19982481,  0.41535033,  1

In [25]:
np.linspace(0,100,20)


array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [26]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [27]:
np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
a[3:4,4:]

array([[20]])

In [36]:

a[3,4]

np.int64(20)

In [40]:
import numpy as np
A = np.arange(0,25) 
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:

from scipy.linalg import svd
a = np.arange(1,19).reshape(6,3) 
U, s, VT = svd(a)
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [43]:
!pip install scipy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 1.1 MB/s eta 0:00:00m eta 0:00:010:00:02


In [45]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [46]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [47]:
U, s, VT = svd(a,full_matrices=True) 
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [48]:
U, s, VT = svd(a,full_matrices=False) 
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [49]:
from numpy import diag 
from numpy import dot 
a= (U @ np.diag(s) @ VT)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])